### ISSUE TITLE
Failed to resolve react/jsx-runtime use react-dnd

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#2813]
### System Info

System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 727.85 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: ^0.1.8 => 0.1.8 
    @rspack/core: ^0.1.8 => 0.1.8 
    @rspack/dev-server: ^0.1.8 => 0.1.8

### Details

when i use react-dnd
```bash
formatted: 'error[internal]: Resolve error\n' +
        '   ┌─ node_modules/.pnpm/react-dnd@16.0.1_jguntkfjozdfrzd4l22x7bdnx4/node_modules/react-dnd/dist/core/DndProvider.js:28:1\n' +
        '   │\n' +
        '28 │ import { jsx as _jsx } from "react/jsx-runtime";\n' +
        '   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Failed to resolve react/jsx-runtime in /project/home/shaodahong/workspace/node_modules/.pnpm/react-dnd@16.0.1_jguntkfjozdfrzd4l22x7bdnx4/node_modules/react-dnd/dist/core/DndProvider.js\n' +
        '\n',
```

but manual import `import jsx from "react/jsx-runtime";` it's normal

### Reproduce link

https://codesandbox.io/p/sandbox/happy-robinson-xwbe9j?file=%2Fsrc%2Fcomponents%2FTestA%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A37%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A4%7D%5D

### Reproduce Steps

1. `pnpm i`
2. `node build.js`

**Comment by hardfist** [comment]
seems a resolve problem, @Boshen can you take a look ?

**Comment by shaodahong** [comment]
> Hey, I didn't replicate it locally, but I'm guessing it's related to `resolve.fullySpecified`, so maybe you can use the following to get around that.
> 
> ```js
> module: {
>     rules: [
>       {
>         test: /\.js$/.
>         resolve: {
>           fullySpecified: false, // disable the behaviour
>         }.
>       }.
>     ].
>   }.
> ```

I use this config to resolve it , and in my Reproduce link i do not use `@rspacl/cli`, only use `@rspacl/core` api, i'm not sure this problem is related to not use `@rspacl/cli`

**Comment by hardfist** [comment]
![image](https://user-images.githubusercontent.com/8898718/234235590-a1947051-7a11-4c45-b139-c497ae41b091.png)
@shaodahong I cant' reproduce it in your demo anymore, can you help check it again

**Comment by shaodahong** [comment]
@hardfist 

Sorry ,i added this config, you need remove it and try

<img width="543" alt="image" src="https://user-images.githubusercontent.com/14831261/234236293-10c930db-048f-4632-af84-2ccfd8c91b54.png">

**Comment by hardfist** [comment]
![image](https://user-images.githubusercontent.com/8898718/234451471-3f367333-be62-4766-a3b5-04121b1ac988.png)
same behavior with webpack, it's a react's bug and it's fixed in react@18

**Comment by bvanjoi** [comment]
Lets me explain that:

- react@17 + react-dnd@16.0.1 will throw an error, it is expected because react-dnd@16.0.1 enabled `type: module` in its package.json, so modules in it are ESM and `resolve.fullySpecified` enabled default, and changed from `import xxx from 'react/jsx-runtime'`  to `import xxx from 'react/jsx-runtime.js'` will fix that.

- react@18 + react-dnd@16.0.1 works because react@18 had defined `exports` in its package.json, it maps `react/jsx-runtime` to `react/jsx-runtime.js`.


so there had two ways to avoid this problem:

- use react@18.
- fix the bug in react-dnd@16.0.1, there has many ways, and lucky it had been fixed by delete `type: module` in package.json in [1c2104](https://github.com/react-dnd/react-dnd/commit/1c2104520ea8db5c42ed90d2dd5595a26cc46c34#diff-c0289e58991b7f04885865bc8fbdaf609edd987130bb8a7df705a007fb0b3852L5) , we can wait to the next version of react-dnd.

**Comment by shaodahong** [comment]
> Lets me explain that:
> 
> * react@17 + react-dnd@16.0.1 will throw an error, it is expected because react-dnd@16.0.1 enabled `type: module` in its package.json, so modules in it are ESM and `resolve.fullySpecified` enabled default, and changed from `import xxx from 'react/jsx-runtime'`  to `import xxx from 'react/jsx-runtime.js'` will fix that.
> * react@18 + react-dnd@16.0.1 works because react@18 had defined `exports` in its package.json, it maps `react/jsx-runtime` to `react/jsx-runtime.js`.
> 
> so there had two ways to avoid this problem:
> 
> * use react@18.
> * fix the bug in react-dnd@16.0.1, there has many ways, and lucky it had been fixed by delete `type: module` in package.json in [1c2104](https://github.com/react-dnd/react-dnd/commit/1c2104520ea8db5c42ed90d2dd5595a26cc46c34#diff-c0289e58991b7f04885865bc8fbdaf609edd987130bb8a7df705a007fb0b3852L5) , we can wait to the next version of react-dnd.

@bvanjoi Oh, thank you for answering so attentively.

**Comment by hardfist** [comment]
close as working as expected

**Comment by Yinboan** [comment]
I'm sorry, I encountered the same problem and I used react@16.8 Although I have read your very professional explanations, as a novice, I still cannot fully understand. If this is caused by my React version being 16.8, is there any way to solve it without upgrading React?

**Comment by hardfist** [comment]
> I'm sorry, I encountered the same problem and I used react@16.8 Although I have read your very professional explanations, as a novice, I still cannot fully understand. If this is caused by my React version being 16.8, is there any way to solve it without upgrading React?
try this
![image](https://github.com/web-infra-dev/rspack/assets/8898718/62bf803c-48b5-40f1-b49d-e957532e0030)
